(add-to-list 'load-path "/home/samuel/.emacs.d/settings/")
;; Indent Fucking Whole Buffer (by github.com/skgsergio)
(defun iwb ()
  "Indent whole buffer"
  (interactive)
  (delete-trailing-whitespace)
  (indent-region (point-min) (point-max) nil)
  (untabify (point-min) (point-max))
  (message "Indent buffer: Done.")
  )
(defun tema ()
  "Ejecuta correctamente el tema"
  (interactive)
  (load-theme 'airline-dark t)
  (message "Done!")
  )
(require 'requirements)
(require 'themes)
(require 'global-modes)
(require 'binds)
(menu-bar-mode -1)
(tool-bar-mode -1)
