(provide 'themes)
;(load-theme 'green-phosphor t)
;(load-theme 'monokai t)
;(load-theme 'atom-dark t)
;(load-theme 'graphene-meta t)
;(load-theme 'dracula t)
;(load-theme 'dakrone t)
;(load-theme 'airline-serene t)
;(load-theme 'airline-behelit t)
;(load-theme 'airline-kolor t)
;(load-theme 'abyss t)
;(load-theme 'airline-kalisi t)
;(load-theme 'airline-ubaryd t)
(load-theme 'airline-dark t)
(load-theme 'airline-dark t)
;(load-theme 'airline-wombat t)					;
;(load-theme 'ahungry t)
(load-theme 'sanityinc-tomorrow-eighties t)
;(load-theme 'tango-dark t)
(add-to-list 'default-frame-alist '(font . "Consolas Medium 10" ))
(set-face-attribute 'default t :font "Consolas Medium 10" )
